---
- name: Init role
  include_role:
    name: elk_docker_compose
    tasks_from: init

- name: Create folders
  file:
    path: "{{ item }}"
    state: directory
    mode: 0777
  with_list: "{{ folders_to_create }}"

- name: Deploy ELK templates
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items: "{{ template_items_to_deploy }}"

- name: Create elk docker-compose.yml and .env files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: 'elk_docker_compose/docker-compose.yml.j2', dest: '{{ elk_stack_host_directory }}/docker-compose.yml' }
    - { src: 'elk_docker_compose/.env.j2', dest: '{{ elk_stack_host_directory }}/.env' }

- name: Install ELK Curator
  include_role:
    name: elk_docker_compose
    tasks_from: curator
  when: curator_install|bool

- name: Start docker compose
  docker_compose:
    project_src: "{{ elk_stack_host_directory }}"
    state: present

#- name: Set index template
#  uri:
#    url: http://localhost:9200/_template/opde
#    method: PUT
#    body_format: json
#    src: ./roles/elk_docker_compose/templates/logstash/opde_index_template.json
