---
- name: Create work dir
  file:
    path: /opt/{{ work_dir }}
    state: directory

- name: Copy templates
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: 'docker-compose.yml', dest: '/opt/{{ work_dir }}/docker-compose.yml' }

- name: Start docker compose
  docker_compose:
    project_src: /opt/{{ work_dir }}
    state: present
