---
- name: Remove old Docker packages
  yum:
    name:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-engine
    state: absent

- name: Install Docker support packages
  yum:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
      - epel-release
    state: present

- name: Add Docker repository
  command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

- name: Install Docker
  yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

- name: Enable and start Docker
  service:
    name: docker
    state: started
    enabled: true

- name: Install pip, python-devel, gcc
  yum:
    name:
    - python-pip
    - python-devel
    - gcc
    state: present

#- name: Upgrade pip
#  command: pip install --upgrade pip
# docker-compose can't be installed with latest version of pip, however old pip can't install zipp
- name: Install docker-compose
  pip:
    name:
    - configparser
    - zipp
    - docker-compose
    state: present

- name: Upgrade pip
  command: pip install --upgrade pip

- name: Install docker-compose requirements
  pip:
    name:
      - configparser
      - zipp
    state: present

#- name: Download docker-compose
#  get_url:
#    url: 'https://github.com/docker/compose/releases/download/1.25.5/docker-compose-Linux-x86_64'
#    checksum: 'sha256:1cb7ecccc17c8d5f1888f9e2b3211b07e35c86d0010a6c0f711fe65ef5b69528'
#    dest: '/usr/local/bin/docker-compose'
#
#- name: Make docker-compose executable
#  file:
#    path: /usr/local/bin/docker-compose
#    mode: '0744'
